"""add member health check config

Revision ID: 3c81dda605a2
Revises: 92e11d193e0d
Create Date: 2026-04-19 07:54:20.898843

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c81dda605a2"
down_revision: str | Sequence[str] | None = "92e11d193e0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member_health_check_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("check_type_id", sa.Integer(), nullable=False),
        sa.Column("period_years", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["check_type_id"], ["health_check_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id"], ["family_members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "check_type_id", name="uq_member_check_config"),
    )
    op.create_index(
        op.f("ix_member_health_check_configs_check_type_id"),
        "member_health_check_configs",
        ["check_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_member_health_check_configs_member_id"),
        "member_health_check_configs",
        ["member_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_member_health_check_configs_member_id"), table_name="member_health_check_configs"
    )
    op.drop_index(
        op.f("ix_member_health_check_configs_check_type_id"),
        table_name="member_health_check_configs",
    )
    op.drop_table("member_health_check_configs")
    # ### end Alembic commands ###
