"""refactor: switch to group-channel based notifications

Revision ID: 4c49e0a4fd5b
Revises: ef6594748355
Create Date: 2026-04-19 02:12:31.110655

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4c49e0a4fd5b"
down_revision: str | Sequence[str] | None = "ef6594748355"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admin_broadcasts", "notification_ids")
    op.drop_column("admin_broadcasts", "target_member_ids")
    op.drop_column("reminder_rules", "target_member_ids")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reminder_rules",
        sa.Column(
            "target_member_ids", postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "admin_broadcasts",
        sa.Column(
            "target_member_ids", postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "admin_broadcasts",
        sa.Column(
            "notification_ids", postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
