"""초기 스키마 생성

Revision ID: 50cad0b53392
Revises:
Create Date: 2026-04-18 15:42:43.278360

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "50cad0b53392"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_broadcasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sent_by", sa.String(length=100), nullable=False),
        sa.Column("target_member_ids", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("notification_ids", sa.ARRAY(sa.Integer()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "family_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("birthday_solar", sa.Date(), nullable=True),
        sa.Column("birthday_lunar", sa.Date(), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_family_members_telegram_user_id"),
        "family_members",
        ["telegram_user_id"],
        unique=True,
    )
    op.create_table(
        "reminder_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "birthday", "holiday", "health_check", "custom", "diet_report", name="remindertype"
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("lead_times_days", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("target_member_ids", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reminder_rules_type"), "reminder_rules", ["type"], unique=False)
    op.create_table(
        "scheduled_notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "failed", "cancelled", name="notificationstatus"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["rule_id"], ["reminder_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_notifications_rule_id"),
        "scheduled_notifications",
        ["rule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_notifications_scheduled_at"),
        "scheduled_notifications",
        ["scheduled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_notifications_status"),
        "scheduled_notifications",
        ["status"],
        unique=False,
    )
    op.create_table(
        "weight_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["member_id"], ["family_members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weight_logs_member_id"), "weight_logs", ["member_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weight_logs_member_id"), table_name="weight_logs")
    op.drop_table("weight_logs")
    op.drop_index(op.f("ix_scheduled_notifications_status"), table_name="scheduled_notifications")
    op.drop_index(
        op.f("ix_scheduled_notifications_scheduled_at"), table_name="scheduled_notifications"
    )
    op.drop_index(op.f("ix_scheduled_notifications_rule_id"), table_name="scheduled_notifications")
    op.drop_table("scheduled_notifications")
    op.drop_index(op.f("ix_reminder_rules_type"), table_name="reminder_rules")
    op.drop_table("reminder_rules")
    op.drop_index(op.f("ix_family_members_telegram_user_id"), table_name="family_members")
    op.drop_table("family_members")
    op.drop_table("admin_broadcasts")
    # ### end Alembic commands ###
