"""add height_cm and diet_active to family_members

Revision ID: 699ca1657399
Revises: d4d0183e6904
Create Date: 2026-04-19 08:36:20.842415

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "699ca1657399"
down_revision: str | Sequence[str] | None = "d4d0183e6904"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("family_members", sa.Column("height_cm", sa.Integer(), nullable=True))
    op.add_column("family_members", sa.Column("diet_active", sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("family_members", "diet_active")
    op.drop_column("family_members", "height_cm")
    # ### end Alembic commands ###
