"""add_health_check_system

Revision ID: 92e11d193e0d
Revises: 4c49e0a4fd5b
Create Date: 2026-04-19 07:36:12.113749

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92e11d193e0d"
down_revision: str | Sequence[str] | None = "4c49e0a4fd5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_check_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("period_years", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(length=1), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "health_check_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("check_type_id", sa.Integer(), nullable=False),
        sa.Column("checked_at", sa.Date(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["check_type_id"], ["health_check_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id"], ["family_members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "check_type_id", "checked_at", name="uq_health_record"),
    )
    op.create_index(
        op.f("ix_health_check_records_check_type_id"),
        "health_check_records",
        ["check_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_check_records_member_id"),
        "health_check_records",
        ["member_id"],
        unique=False,
    )
    op.add_column("family_members", sa.Column("gender", sa.String(length=1), nullable=True))
    op.add_column(
        "scheduled_notifications", sa.Column("source_key", sa.String(length=200), nullable=True)
    )
    op.create_index(
        op.f("ix_scheduled_notifications_source_key"),
        "scheduled_notifications",
        ["source_key"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_scheduled_notifications_source_key"), table_name="scheduled_notifications"
    )
    op.drop_column("scheduled_notifications", "source_key")
    op.drop_column("family_members", "gender")
    op.drop_index(op.f("ix_health_check_records_member_id"), table_name="health_check_records")
    op.drop_index(op.f("ix_health_check_records_check_type_id"), table_name="health_check_records")
    op.drop_table("health_check_records")
    op.drop_table("health_check_types")
    # ### end Alembic commands ###
