"""add min_age to health_check_types

Revision ID: d4d0183e6904
Revises: 3c81dda605a2
Create Date: 2026-04-19 07:58:43.674950

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4d0183e6904"
down_revision: str | Sequence[str] | None = "3c81dda605a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("health_check_types", sa.Column("min_age", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("health_check_types", "min_age")
    # ### end Alembic commands ###
