"""scheduled_notifications rule_id nullable 수정

Revision ID: ef6594748355
Revises: 50cad0b53392
Create Date: 2026-04-18 15:54:22.692461

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef6594748355"
down_revision: str | Sequence[str] | None = "50cad0b53392"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("scheduled_notifications", "rule_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scheduled_notifications", "rule_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
